(meta-source "fn/parse")

;; ═══════════════════════════════════════════════════
;; 函数语法解析
;; ═══════════════════════════════════════════════════

(define (parse-params-tail cursor acc)
  (let* ((name (syntax.cursor-match-ident! cursor)))
    (if (optional.none? name)
        (begin (syntax.cursor-expect-eof! cursor) (list.reverse acc))
        (let* ((_colon (syntax.cursor-expect-punct! cursor '|:|))
               (ty (parse-type cursor))
               (comma (syntax.cursor-match-punct! cursor '|,|))
               (param (lain-quote `(param ,(optional.value name) ,ty))))
          (if (optional.none? comma)
              (begin (syntax.cursor-expect-eof! cursor) (list.reverse (list.cons param acc)))
              (parse-params-tail cursor (list.cons param acc)))))))

(define (parse-params group)
  (let* ((cursor (syntax.group-cursor group)))
    (parse-params-tail cursor (list))))

(define (parse-empty-params group)
  (let* ((cursor (syntax.group-cursor group))
         (_eof (syntax.cursor-expect-eof! cursor)))
    (list)))

(define (parse-optional-fn-body cursor)
  (let* ((semi (syntax.cursor-match-punct! cursor '|;|)))
    (if (optional.some? semi)
        (optional.none)
        (optional.some (parse-block (syntax.cursor-expect-group! cursor '|brace|))))))

(define-pass (form-parser |fn| form)
  (let* ((cursor (syntax.form-cursor form))
         (attrs (parse-attrs cursor (list)))
         (_kw (syntax.cursor-expect-ident! cursor))
         (name (syntax.cursor-expect-ident! cursor))
         (generics (parse-generic-params cursor))
         (params (parse-params (syntax.cursor-expect-group! cursor '|paren|)))
         (arrow (syntax.cursor-match-punct! cursor '|->|))
         (ret (if (optional.some? arrow)
                  (parse-type cursor)
                  (lain-quote '(type-unit))))
         (effects (parse-optional-effects cursor))
         (where (parse-where cursor))
         (body (parse-optional-fn-body cursor))
         (_eof (syntax.cursor-expect-eof! cursor))
         ;; Unified let node: wraps old |fn.sig| payload under |let| with type-kind = |fn|
         (sig-payload (record '|fn.sig|
                        (record.field '|attrs| attrs) (record.field '|generics| generics)
                        (record.field '|params| params) (record.field '|return| ret)
                        (record.field '|where| where) (record.field '|effects| effects)
                        (record.field '|body| body)))
         (unified (raw.node! '|let|
                    (record '|let|
                      (record.field '|name| name)
                      (record.field '|type-kind| '|fn|)
                      (record.field '|payload| sig-payload)))))
    (if (fn.cfg-enabled? attrs) (decl.define-dup-checked! '|let| name unified) unit)))

(define-pass (form-parser |pub| form)
  (let* ((cursor (syntax.form-cursor form))
         (attrs (parse-attrs cursor (list)))
         (_pub (syntax.cursor-expect-ident! cursor))
         (next (syntax.cursor-match-ident! cursor)))
    (cond ((optional.none? next) unit)
          ((symbol=? (optional.value next) '|fn|)
           (let* ((name (syntax.cursor-expect-ident! cursor))
                  (generics (parse-generic-params cursor))
                  (params (parse-params (syntax.cursor-expect-group! cursor '|paren|)))
                  (arrow (syntax.cursor-match-punct! cursor '|->|))
                  (ret (if (optional.some? arrow) (parse-type cursor) (lain-quote '(type-unit)))) (effects (parse-optional-effects cursor))
                  (where (parse-where cursor)) (body (parse-optional-fn-body cursor))
                  (_eof (syntax.cursor-expect-eof! cursor))
                  (sig-payload (record '|fn.sig|
                         (record.field '|public| #t) (record.field '|attrs| attrs)
                         (record.field '|generics| generics) (record.field '|params| params)
                         (record.field '|return| ret) (record.field '|where| where)
                         (record.field '|effects| effects) (record.field '|body| body)))
                  (unified (raw.node! '|let|
                             (record '|let|
                               (record.field '|name| name)
                               (record.field '|type-kind| '|fn|)
                               (record.field '|payload| sig-payload)))))
             (if (fn.cfg-enabled? attrs) (decl.define-dup-checked! '|let| name unified) unit)))
          ((symbol=? (optional.value next) '|struct|)
           (let* ((name (syntax.cursor-expect-ident! cursor))
                  (generics (parse-generic-params cursor)) (where (parse-where cursor))
                  (body (syntax.cursor-expect-group! cursor '|brace|))
                  (_eof (syntax.cursor-expect-eof! cursor))
                  (body-cursor (syntax.group-cursor body))
                  (fields (pub.struct-parse-fields body-cursor (list)))
                  (inner-payload (record '|struct|
                           (record.field '|public| #t) (record.field '|attrs| attrs)
                           (record.field '|generics| generics) (record.field '|where| where)
                           (record.field '|fields| fields)))
                  (unified (raw.node! '|let|
                             (record '|let|
                               (record.field '|name| name)
                               (record.field '|type-kind| '|struct|)
                               (record.field '|payload| inner-payload)))))
             (if (fn.cfg-enabled? attrs) (decl.define-dup-checked! '|let| name unified) unit)))
          (else unit))))

(define (pub.struct-parse-fields cursor acc)
  (let* ((name (syntax.cursor-match-ident! cursor)))
    (if (optional.none? name)
        (begin (syntax.cursor-expect-eof! cursor) (list.reverse acc))
        (let* ((_colon (syntax.cursor-expect-punct! cursor '|:|))
               (ty (parse-type cursor))
               (semi (syntax.cursor-match-punct! cursor '|;|))
               (_comma (if (optional.none? semi) (syntax.cursor-match-punct! cursor '|,|) unit))
               (field (raw.node! '|struct.field| (record '|struct.field|
                         (record.field '|name| (optional.value name))
                         (record.field '|type| ty)))))
          (pub.struct-parse-fields cursor (list.cons field acc))))))
