(meta-source "struct/lower")

(define (struct.lower-field-types fields acc)
  (if (list.empty? fields) (list.reverse acc)
      (let* ((field (list.first fields)) (payload (middle.payload field)))
        (struct.lower-field-types (list.rest fields)
          (list.cons (record '|struct.core-field|
                       (record.field '|name| (optional.value (record.get payload '|name|)))
                       (record.field '|type| (core.lower-type (optional.value (record.get payload '|type|)))))
                     acc)))))

(define-pass (core-declarer |middle.struct| item)
  (let* ((payload (middle.payload item))
         (name (optional.value (record.get payload '|name|)))
         (fields (optional.value (record.get payload '|fields|))))
    (core.declare-struct! name (struct.lower-field-types fields (list)))))

(define (struct.lower-literal-fields block struct-name fields locals acc)
  (if (list.empty? fields) (list.reverse acc)
      (let* ((field (list.first fields)) (payload (middle.payload field))
             (name (optional.value (record.get payload '|name|)))
             (value-expr (optional.value (record.get payload '|value|)))
             (field-ty (core.struct-field-type struct-name name))
             (value (core.lower-expr block value-expr field-ty locals)))
        (struct.lower-literal-fields block struct-name (list.rest fields) locals (list.cons value acc)))))

(define-pass (core-expr-lowerer |middle.expr.struct| block expr expected-ty locals)
  (let* ((payload (middle.payload expr))
         (name (optional.value (record.get payload '|name|)))
         (fields (optional.value (record.get payload '|fields|))))
    (core.aggregate! block (core.struct-type name)
      (struct.lower-literal-fields block name fields locals (list)))))

(define-pass (core-expr-inferer |middle.expr.struct| expr locals)
  (let* ((payload (middle.payload expr))
         (name (optional.value (record.get payload '|name|))))
    (core.struct-type name)))

(define-pass (core-expr-lowerer |middle.expr.field| block expr expected-ty locals)
  (let* ((payload (middle.payload expr))
         (base-expr (optional.value (record.get payload '|base|)))
         (field-name (optional.value (record.get payload '|field|)))
         (base-ty (core.infer-expr-type base-expr locals)))
    (core.field! block (core.lower-expr block base-expr base-ty locals)
      base-ty (core.struct-field-index-from-type base-ty field-name)
      (core.struct-field-type-from-type base-ty field-name))))

(define-pass (core-expr-inferer |middle.expr.field| expr locals)
  (let* ((payload (middle.payload expr))
         (base (optional.value (record.get payload '|base|)))
         (field-name (optional.value (record.get payload '|field|))))
    (core.struct-field-type-from-type (core.infer-expr-type base locals) field-name)))
