(meta-source "control/match")
(define (parse-match-arrow cursor)(syntax.cursor-expect-punct! cursor '|=>|))
(define (parse-match-pattern cursor)(let*((name(syntax.cursor-expect-ident! cursor)))(if(symbol=? name '|_|)(raw.node! '|match.pattern.wildcard|(record '|match.pattern.wildcard|))(let*((paren(syntax.cursor-match-group! cursor '|paren|)))(if(optional.none? paren)(raw.node! '|match.pattern.variant|(record '|match.pattern.variant|(record.field '|name| name)(record.field '|binding|(optional.none))))(let*((body(syntax.group-cursor(optional.value paren)))(binding(syntax.cursor-expect-ident! body)))(syntax.cursor-expect-eof! body)(raw.node! '|match.pattern.variant|(record '|match.pattern.variant|(record.field '|name| name)(record.field '|binding|(optional.some binding))))))))))
(define (parse-match-arm cursor)(let*((pattern(parse-match-pattern cursor))(_arrow(parse-match-arrow cursor))(body(syntax.parse-block(syntax.cursor-expect-group! cursor '|brace|))))(raw.node! '|match.arm|(record '|match.arm|(record.field '|pattern| pattern)(record.field '|body| body)))))
(define (parse-match-arms cursor acc)(if(syntax.cursor-eof? cursor)(list.reverse acc)(let*((arm(parse-match-arm cursor))(_comma(syntax.cursor-match-punct! cursor '|,|)))(parse-match-arms cursor(list.cons arm acc)))))
(define (parse-match-expr cursor)(let*((scrutinee(parameterize((*allow-struct-literal* #f))(syntax.parse-expr cursor)))(brace(syntax.cursor-expect-group! cursor '|brace|))(body-cursor(syntax.group-cursor brace))(arms(parse-match-arms body-cursor(list))))(syntax.cursor-expect-eof! body-cursor)(raw.node! '|expr.match|(record '|expr.match|(record.field '|scrutinee| scrutinee)(record.field '|arms| arms)))))
(register-expr-parser! '|match| parse-match-expr)
(define (middle.normalize-match-arms-helper raw-arms acc)(if(list.empty? raw-arms)(list.reverse acc)(let*((raw-arm(list.first raw-arms))(arm-payload(raw.payload raw-arm))(pattern(optional.value(record.get arm-payload '|pattern|)))(body-raw(optional.value(record.get arm-payload '|body|)))(body-mid(middle.normalize-block body-raw))(pattern-kind(raw.kind pattern))(pattern-payload(raw.payload pattern))(pname(if(symbol=? pattern-kind '|match.pattern.variant|)(optional.value(record.get pattern-payload '|name|))'|_|))(pbinding(if(symbol=? pattern-kind '|match.pattern.variant|)(record.get pattern-payload '|binding|)(optional.none))))(middle.normalize-match-arms-helper(list.rest raw-arms)(list.cons(record '|middle.match.arm|(record.field '|pattern-kind| pattern-kind)(record.field '|pattern-name| pname)(record.field '|pattern-binding| pbinding)(record.field '|body| body-mid))acc)))))
(define-pass (middle-normalizer |expr.match| raw-expr)(let*((payload(raw.payload raw-expr))(scrutinee(middle.normalize-expr(optional.value(record.get payload '|scrutinee|))))(raw-arms(optional.value(record.get payload '|arms|))))(middle.node! '|control.match|(record '|control.match|(record.field '|scrutinee| scrutinee)(record.field '|arms|(middle.normalize-match-arms-helper raw-arms(list)))))))

;; Stub: match is now handled through core-stmt-lowerer (like if/else).
;; This expr-lowerer returns a dummy value and should never be called —
;; the stmt-lowerer intercepts match before core.lower-expr dispatches here.
(define-pass (core-expr-lowerer |control.match| block expr expected-ty locals)
  (core.const-bits! block (core.make-bits 32) 0))
