[workspace]
name = "lain-lang"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64","linux-64"]

[dependencies]
llvmdev = ">=22.1,<23"
clang = ">=22.1,<23"
lld = ">=22.1,<23"
zlib = ">=1.3,<2"
libxml2 = ">=2.15.3,<3"
libxml2-devel = ">=2.15.3,<3"
llvm = ">=22.1.7,<23"

[tasks]
fmt = "cargo fmt"
fmt-check = "cargo fmt -- --check"
clippy = "cargo clippy --all-targets -- -D warnings"
test = "cargo test"
build = "cargo build"
llvm-version = "llvm-config --version"
clang-version = "clang --version"

