#ifndef LAIN_VERSION_H
#define LAIN_VERSION_H

#define LAIN_VERSION "0.1.0-alpha.1"
#define LAIN_IR_SCHEMA_VERSION 1
#define LAIN_COMPILER_API_SCHEMA_VERSION 1
#define LAIN_MODULE_ARTIFACT_SCHEMA_VERSION 1

#endif
