std_version = "0.1.0"
language_edition = "2026"
meta_abi = 1
runtime_abi = 1

meta_sources = [
    "meta/core/list.scm",
    "meta/core/record.scm",
    "meta/core/types.scm",
    "meta/core/memory.scm",
    "meta/core/literals.scm",
    "meta/core/call.scm",
    "meta/io/println.scm",
    "meta/effects/base.scm",
    "meta/effects/throws.scm",
    "meta/effects/suspend.scm",
    "meta/effects/spawn.scm",
    "meta/operators/integer.scm",
    "meta/operators/question.scm",
    "meta/syntax/common.scm",
    "meta/lang/fn.scm",
    "meta/lang/import.scm",
    "meta/lang/struct.scm",
    "meta/lang/enum.scm",
    "meta/lang/effect.scm",
    "meta/lang/interface.scm",
    "meta/lang/impl.scm",
    "meta/middle/common.scm",
    "meta/core/lower.scm",
]

runtime_sources = [
    "io.lain",
    "fs.lain",
    "process.lain",
    "env.lain",
]

