std_version = "0.1.0"
language_edition = "2026"
meta_abi = 1
runtime_abi = 1

meta_sources = [
    "meta/derive/clone.scm",
    "meta/foreign.scm",
    "meta/effect.scm",
    "meta/interface.scm",
    "meta/macros/format.scm",
    "meta/operators/question.scm",
]
